travis:
  secure:
    BINSTAR_TOKEN: cSKyHHlxJqkHr7a4iwqN/OSZwalOSjDB8mog0fkMzISnll5+Y5/gBDs/2InX7z/dt44kVAVnhZ8xgKHI9CCrUkCiB7r4ixHVuKfbL/ltBi8lxDFIrXr6tgy7b0d753z7JquE+jMfgKtrQkLzsPE+e2TbeRuCEpXyEgRxZImp31akuy5vxyZL6MqNQyfnmA/RdRVYAiCo83DJwUBZdXm8pZsGoMaGHOh7iwsUTC+LsY+tThA7ffic+FtOn81E1a0gcF1P9cHpR+jIwCcdUrTTlQDobJR08Z5FlfLX0uWM2rfcA6JDDBuip67p6p8UpjPfQ5vAATw4KcIgdgUFQIeJnykLLoU3+OzengQZ0CaR9KtBRO/3T1y+1R/KVFVvKGZeuLpRHwtByhVNyCWCpPEqPTrXCN4LDVgS8rQSFIcp/GWfWO7C6t1aQ+rOzKfiQdhf+ZMbaU5a3Z7bEvSJQSYOPb3NGxXGKj3se1Z5ntjhW/T/m3FUo4P7Mqa5YNknpbPlp03nyo7p2lc99qWQ4mF9ESBH9yJi8HLxJ8uXEq9s7W/kZMydbY8zVX5UJqM6SBv77MDzs9dF3HnYEVNSeIPpJBZwF1s+MR180PoFsPjASZMvZY05whvmxUFL1UxF7qbkPewy/4otI8Tp0hWHEkCCVB0RsEbiIEYsQXGuGEBZPWM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
